.dashExtraUiComponents_js_metadata <- function() {
deps_metadata <- list(`dash_extra_ui_components` = structure(list(name = "dash_extra_ui_components",
version = "0.0.2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_extra_ui_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtraUiComponents",
all_files = FALSE), class = "html_dependency"),
`dash_extra_ui_components` = structure(list(name = "dash_extra_ui_components",
version = "0.0.2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_extra_ui_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashExtraUiComponents",
all_files = FALSE), class = "html_dependency"),
`dash_extra_ui_components` = structure(list(name = "dash_extra_ui_components",
version = "0.0.2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'nova-light/theme.css', head = NULL, attachment = NULL, package = "dashExtraUiComponents",
all_files = FALSE), class = "html_dependency"),
`dash_extra_ui_components` = structure(list(name = "dash_extra_ui_components",
version = "0.0.2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'primeicons/primeicons.css', head = NULL, attachment = NULL, package = "dashExtraUiComponents",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
