.extraDashUiComponents_js_metadata <- function() {
deps_metadata <- list(`extra_dash_ui_components` = structure(list(name = "extra_dash_ui_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'extra_dash_ui_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "extraDashUiComponents",
all_files = FALSE), class = "html_dependency"),
`extra_dash_ui_components` = structure(list(name = "extra_dash_ui_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'extra_dash_ui_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "extraDashUiComponents",
all_files = FALSE), class = "html_dependency"),
`extra_dash_ui_components` = structure(list(name = "extra_dash_ui_components",
version = "2", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'nova-light/theme.css', head = NULL, attachment = NULL, package = "extraDashUiComponents",
all_files = FALSE), class = "html_dependency"),
`extra_dash_ui_components` = structure(list(name = "extra_dash_ui_components",
version = "3", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'primereact/primereact.min.css', head = NULL, attachment = NULL, package = "extraDashUiComponents",
all_files = FALSE), class = "html_dependency"),
`extra_dash_ui_components` = structure(list(name = "extra_dash_ui_components",
version = "4", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'primeicons/primeicons.css', head = NULL, attachment = NULL, package = "extraDashUiComponents",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
